### ISSUE TITLE
italy_map_province %>% mapview(zcol = "total_cases") not showing in the view tab of Rstudio 4.0.0

### ISSUE THREAD

**Issue by maklaskarlos** [Covid19R/covid19italy#8]
When I run italy_map_province %>% mapview(zcol = "total_cases") it does not show anything. Even mapview(breweries) takes a lot of time to appear in the view tab of R studio.

**Comment by RamiKrispin** [comment]
Hi @maklaskarlos, could be you are missing some of the components required to run the **mapview**. Could you please provides the output of the following:
```
packageVersion("covid19italy")
packageVersion("mapview")
packageVersion("rnaturalearth")
```

Also, if you are running the code below with **ggplot2**, are you getting the plot?
```
library(ggplot2)
ggplot(data = italy_map_province, aes(fill = `total_cases`)) + 
  geom_sf() + 
  scale_fill_viridis_b()
```

**Comment by maklaskarlos** [comment]
> packageVersion("covid19italy")
[1] ‘0.2.0’
> packageVersion("mapview")
[1] ‘2.7.8’
> packageVersion("rnaturalearth")
[1] ‘0.1.0’

ggplot2 its ok. I see the map perfectly.

**Comment by RamiKrispin** [comment]
Are you able to run `mapview(breweries)`?

**Comment by maklaskarlos** [comment]
Not really. After several times trying to visualize it, I got only once and it took ages. An also only the points where showing, not the map in the background.

**Comment by RamiKrispin** [comment]
I think you have either conflict or some driver missing that prevent `mapview` function to run. I would recommend trying to reinstall the **mapview** package and make sure that all the dependencies are updated. If still not working I would recommend checking on the **mapview** package [issue](https://github.com/r-spatial/mapview/issues) page (mainly on the closed issues page). I found this issue may relevant:
https://github.com/r-spatial/mapview/issues/153

**Comment by maklaskarlos** [comment]
thank you very much Rami!

**Comment by maklaskarlos** [comment]
#devtools::install_github("r-spatial/mapview@develop") 3-none option
#install.packages("mapview")
library(mapview)

...and I was able to visualize mapview(breweries) correctly, although it took some time. May be is my computer the reason of not having the italy_map_province %>% mapview(zcol = "total_cases") map
